// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGbu-ZftIrEgTKNbP6h0TZLhAPkmwLc_k',
    appId: '1:673332842441:web:bd170f2c258ffd3b926218',
    messagingSenderId: '673332842441',
    projectId: 'tricpro-dfd21',
    authDomain: 'tricpro-dfd21.firebaseapp.com',
    storageBucket: 'tricpro-dfd21.firebasestorage.app',
    measurementId: 'G-EBGXNVSGG1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6c8U73wmNuCwL-1CNWQwbPzHWjscZH0k',
    appId: '1:673332842441:android:1eef8aaecb817206926218',
    messagingSenderId: '673332842441',
    projectId: 'tricpro-dfd21',
    storageBucket: 'tricpro-dfd21.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdhKolqSj1dMn9gyYD4YqJKiUOZB8j79U',
    appId: '1:673332842441:ios:f99d6b8d62c8ac79926218',
    messagingSenderId: '673332842441',
    projectId: 'tricpro-dfd21',
    storageBucket: 'tricpro-dfd21.firebasestorage.app',
    iosBundleId: 'everem.reminder.com',
  );
}
